-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 18:11:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookInventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookInventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookInventory` DEFAULT CHARACTER SET utf8 ;
USE `bookInventory` ;

-- -----------------------------------------------------
-- Table `bookInventory`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookInventory`.`users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(50) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `postal` VARCHAR(6) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookInventory`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookInventory`.`books` (
  `bookID` INT NOT NULL AUTO_INCREMENT,
  `bookname` VARCHAR(50) NOT NULL,
  `author` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`bookID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookInventory`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookInventory`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `bookID` INT NOT NULL,
  PRIMARY KEY (`orderID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
